---
# tasks file for my_mysql_role

- name: Install MySQL server
  package:
    name: mysql-server
    state: present
 
- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true
    
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install python MySQL package
  pip:
    name: pymysql
    state: present

- name: Create a new MySQL database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: localhost
    name: userdb
    state: import
    target: /root/lab_ansible_modulo5_green/roles/mysqldb/files/dump.sql 
    collation: utf8_general_ci


- name: Create a MySQL user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: localhost
    name: demo
    password: demo
    priv: '*.*:ALL'
    state: present

- name: Install MySQL Extension for PHP
  apt:
    name: php-mysql
    state: present

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Install PHP script with database
  copy: src=db.php dest=/var/www/html/db.php mode=6777

